### ISSUE TITLE
Adding USC users to the group

### ISSUE THREAD

**Issue by jeffsiu** [informatics-isi-edu/gpcr-www#1]
Name: Martin Audet
GitHub: audemart

**Comment by jeffsiu** [comment]
Name: Kyle McClary
GitHub: kmcclary

**Comment by jeffsiu** [comment]
Name: Matthew Eddy
GitHub: eddymt

**Comment by jeffsiu** [comment]
Name: Kate White
GitHub: klwhite2

**Comment by jeffsiu** [comment]
Name: Ming Lee
GitHub: mingyuelee

**Comment by hongsudt** [comment]
I think they can generate issues without us doing anything.. 

Do you want the users to write to the wiki pages?

**Comment by jeffsiu** [comment]
I think it is a good idea if they can submit issues directly on the page.

**Comment by hongsudt** [comment]
They can do that directly on the public repo, so no other setting is
required.

However, if you want them to write to the wiki page, then we will need to
add them to the collaborator list.

**Comment by jeffsiu** [comment]
Is informatics-isi-edu/gpcr-www a public repo to write? or do you mean something else?
